#!/bin/env bash

readarray -t exts < <(jq -r '(.require//{}) * (."require-dev"//{})|to_entries|map(select(.key|startswith("ext-"))|.key|split("-")[1])|.[]' <composer.json)

if [ ${#exts[@]} -eq 0 ]; then
	exit
fi

install-php-extensions "${exts[@]}"
