---
name: Update PHP Docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "00 6 * * *"

permissions:
  contents: read

jobs:
  php-update:
    name: Update PHP Docker image SHAs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: "Run update script"
        run: ./bin/update-php-images-sha.sh
      - name: Check for changes
        run: git diff --exit-code
        id: diff
        continue-on-error: true
      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v5
        if: steps.diff.outcome == 'failure'
        with:
          add-paths: Dockerfile
          commit-message: Update PHP Docker image SHAs
          branch: update-php-docker-image-shas
          delete-branch: true
          title: Update PHP Docker image SHAs
          token: ${{ secrets.PAT_TOKEN }}
          team-reviewers: developers
